import 'package:pushtidham/model/bethakji_model.dart';
import 'package:sqflite/sqflite.dart';
import 'package:path/path.dart';

class DatabaseHelper {
  static Database? _database;

  final List<BethakjiModel> bethakji84List = [
    // 1 to 10
    BethakjiModel(
      id: '1',
      number: '1',
      name: 'શ્રી ગોવિંદઘાટ બેઠકજી (ગોકુલ)',
      address: 'શ્રી ગોવિંદ ઘાટ, ગોકુલ - 281303, જી. મથુરા (ઉત્તર પ્રદેશ)',
      contacts: [
        {'label': 'મુખ્યાજી', 'phone': '+91 9358706176'},
      ],
      mahatmy:
          'અહીં શ્રી મહાપ્રભુજીએ શ્રીજીબાવા પાસે બ્રહ્મસંબંધ મંત્ર પ્રાપ્ત કર્યો હતો.',
      directions: 'મથુરાથી ગોકુલ 12 કિ.મી.',
      rules: ['મંદિરમાં શાંતિ જાળવવી', 'પરંપરાગત વસ્ત્રો પહેરવા'],
    ),
    BethakjiModel(
      id: '2',
      number: '2',
      name: 'શ્રી મોટી બેઠકજી (ગોકુલ)',
      address: 'શ્રી મોટી બેઠકજી, ગોકુલ - 281303, જી. મથુરા (ઉત્તર પ્રદેશ)',
      contacts: [
        {'label': 'મુખ્યાજી', 'phone': '+91 9758097493'},
      ],
      mahatmy: 'શ્રી ઠકુરાણી ઘાટ પાસે આવેલ મનોહર સ્થાન.',
      directions: 'ઠકુરાણી ઘાટ નજીક, ગોકુલ',
      rules: ['શાંતિ જાળવવી'],
    ),
    BethakjiModel(
      id: '3',
      number: '3',
      name: 'શ્રી શય્યા મંદિર બેઠકજી (ગોકુલ)',
      address:
          'શ્રી દ્વારકાધીશ મંદિર, ગોકુલ - 281303, જી. મથુરા (ઉત્તર પ્રદેશ)',
      contacts: [],
      mahatmy: 'દ્વારકાધીશ મંદિરમાં આવેલ પવિત્ર બેઠકજી.',
      directions: 'ગોકુલ ગામમાં દ્વારકાધીશ મંદિર',
      rules: [],
    ),
    BethakjiModel(
      id: '4',
      number: '4',
      name: 'શ્રી બંશીબટ બેઠકજી (વૃંદાવન)',
      address: 'બંશીબટ, વૃંદાવન - 281121, જી. મથુરા (ઉત્તર પ્રદેશ)',
      contacts: [],
      mahatmy: 'વૃંદાવનના બંશીબટ ક્ષેત્રમાં સ્થિત બેઠકજી.',
      directions: 'વૃંદાવન ધામ',
      rules: [],
    ),
    BethakjiModel(
      id: '5',
      number: '5',
      name: 'શ્રી વિશ્રામ ઘાટ બેઠકજી (મથુરા)',
      address: 'વિશ્રામ ઘાટ, મથુરા - 281001 (ઉત્તર પ્રદેશ)',
      contacts: [],
      mahatmy: 'યમુના કિનારે વિશ્રામ ઘાટ પર સ્થિત.',
      directions: 'મથુરા યમુના ઘાટ',
      rules: [],
    ),
    BethakjiModel(
      id: '6',
      number: '6',
      name: 'શ્રી મધુબન બેઠકજી',
      address: 'મહૌલી ગામ, જી. મથુરા (ઉત્તર પ્રદેશ)',
      contacts: [],
      mahatmy: 'શ્રી ગુસાંઈજીની પણ બેઠકજી અહીં બિરાજે છે.',
      directions: 'મથુરાથી મહૌલી રોડ',
      rules: [],
    ),
    BethakjiModel(
      id: '7',
      number: '7',
      name: 'શ્રી કામોદવન બેઠકજી',
      address: 'પો. ઉસપાર, જી. મથુરા (ઉત્તર પ્રદેશ)',
      contacts: [],
      mahatmy: 'કામોદવન પવિત્ર વન ક્ષેત્ર.',
      directions: 'મથુરાથી 20 કિ.મી.',
      rules: [],
    ),
    BethakjiModel(
      id: '8',
      number: '8',
      name: 'શ્રી બહુલૌવન બેઠકજી',
      address: 'પો. બાટી ગામ, જી. મથુરા (ઉત્તર પ્રદેશ)',
      contacts: [
        {'label': 'મુખ્યાજી', 'phone': '+91 9837621857'},
      ],
      mahatmy: 'બહુલા ગાયની પવિત્ર કથાનું સ્થાન.',
      directions: 'બાટી ગામ, મથુરા',
      rules: [],
    ),
    BethakjiModel(
      id: '9',
      number: '9',
      name: 'શ્રી રાધાકૃષ્ણ કુંડ બેઠકજી',
      address: 'પો. રાધાકુંડ - 281504, જી. મથુરા (ઉત્તર પ્રદેશ)',
      contacts: [
        {'label': 'દયાલજી મુખ્યાજી', 'phone': '+91 9897407556'},
      ],
      mahatmy: 'શ્રી રાધાકુંડ પરિક્રમા માર્ગ પર સ્થિત.',
      directions: 'રાધાકુંડ',
      rules: [],
    ),
    BethakjiModel(
      id: '10',
      number: '10',
      name: 'શ્રી માનસી ગંગા બેઠકજી',
      address:
          'વલ્લભ ઘાટ, માનસી ગંગા, ગોવર્ધન - 281502, જી. મથુરા (ઉત્તર પ્રદેશ)',
      contacts: [
        {'label': 'જગદીશભાઈ મુખ્યાજી', 'phone': '+91 9758194827'},
      ],
      mahatmy: 'ચકલેશ્વર મહાદેવ પાસે માનસી ગંગા ઘાટ.',
      directions: 'ગોવર્ધન માનસી ગંગા',
      rules: [],
    ),

    // 11 to 20
    BethakjiModel(
      id: '11',
      number: '11',
      name: 'શ્રી ચંદ્ર સરોવર બેઠકજી',
      address: 'પરાસોલી, પો. ગોવર્ધન - 281502, જી. મથુરા (ઉત્તર પ્રદેશ)',
      contacts: [],
      mahatmy: 'ચંદ્ર સરોવર પરાસોલી રાસસ્થળી.',
      directions: 'ગોવર્ધન પરાસોલી',
      rules: [],
    ),
    BethakjiModel(
      id: '12',
      number: '12',
      name: 'શ્રી આણ્યોર બેઠકજી',
      address: 'સદુ પાંડેના મકાનમાં, આણ્યોર - 281502, જી. મથુરા (ઉત્તર પ્રદેશ)',
      contacts: [],
      mahatmy: 'સદુ પાંડેના ઘરે શ્રીજીબાવાએ સામગ્રી આરોગી હતી.',
      directions: 'આણ્યોર ગામ, ગિરિરાજજી',
      rules: [],
    ),
    BethakjiModel(
      id: '13',
      number: '13',
      name: 'શ્રી ગોવિંદ કુંડ બેઠકજી',
      address: 'ગોવિંદ કુંડ, પો. આણ્યોર - 281502, જી. મથુરા (ઉત્તર પ્રદેશ)',
      contacts: [],
      mahatmy: 'ગિરિરાજ પરિક્રમા માર્ગ પર આવેલ ગોવિંદ કુંડ.',
      directions: 'આણ્યોર નજીક ગોવિંદ કુંડ',
      rules: [],
    ),
    BethakjiModel(
      id: '14',
      number: '14',
      name: 'શ્રી સુંદર શીલા બેઠકજી',
      address: 'મુખારવિંદ પાસે, જતીપુરા - 281502, જી. મથુરા (ઉત્તર પ્રદેશ)',
      contacts: [],
      mahatmy: 'સુંદર શીલા ગિરિરાજજી તળેટી.',
      directions: 'જતીપુરા ગિરિરાજજી',
      rules: [],
    ),
    BethakjiModel(
      id: '15',
      number: '15',
      name: 'શ્રી ગિરિરાજજી બેઠકજી (ગુપ્ત બેઠક)',
      address:
          'શ્રીનાથજી મંદિર, ગિરિરાજજી ઉપર, જતીપુરા - 281502 (ઉત્તર પ્રદેશ)',
      contacts: [],
      mahatmy: 'શ્રીનાથજીના મૂળ મંદિર પર સ્થિત ગુપ્ત બેઠકજી.',
      directions: 'જતીપુરા ગિરિરાજજી ઉપર',
      rules: [],
    ),
    BethakjiModel(
      id: '16',
      number: '16',
      name: 'શ્રી કામવન બેઠકજી',
      address: 'શ્રી કુંડ, કામવન (કામા) - 321022, જી. ભરતપુર (રાજસ્થાન)',
      contacts: [],
      mahatmy: 'કામવન સ્થિત પવિત્ર સ્થાન.',
      directions: 'કામા, રાજસ્થાન',
      rules: [],
    ),
    BethakjiModel(
      id: '17',
      number: '17',
      name: 'શ્રી ગહવરવન બેઠકજી',
      address: 'મોરકુટી નીચે, બરસાના, જી. મથુરા (ઉત્તર પ્રદેશ)',
      contacts: [],
      mahatmy: 'બરસાના રાધાજી મંદિર નજીક.',
      directions: 'બરસાના ધામ',
      rules: [],
    ),
    BethakjiModel(
      id: '18',
      number: '18',
      name: 'શ્રી સંકેતવન બેઠકજી',
      address: 'કૃષ્ણ કુંડ બગીચામાં, બરસાના, જી. મથુરા (ઉત્તર પ્રદેશ)',
      contacts: [],
      mahatmy: 'રાધા-કૃષ્ણ મિલન સંકેત સ્થાન.',
      directions: 'બરસાના સંકેતવન',
      rules: [],
    ),
    BethakjiModel(
      id: '19',
      number: '19',
      name: 'શ્રી નંદગામ બેઠકજી',
      address: 'પાન સરોવર, નંદગામ - 281403, જી. મથુરા (ઉત્તર પ્રદેશ)',
      contacts: [],
      mahatmy: 'નંદ બાબાના નંદગામ સ્થિત પાન સરોવર.',
      directions: 'નંદગામ પાન સરોવર',
      rules: [],
    ),
    BethakjiModel(
      id: '20',
      number: '20',
      name: 'શ્રી કોકિલાવન બેઠકજી',
      address: 'જાંવ, કોકિલાવન, જી. મથુરા (ઉત્તર પ્રદેશ)',
      contacts: [],
      mahatmy: 'કોકિલાવન ભજન સ્થાન.',
      directions: 'કોકિલાવન',
      rules: [],
    ),

    // 21 to 30
    BethakjiModel(
      id: '21',
      number: '21',
      name: 'શ્રી ભાંડીરવન બેઠકજી',
      address: 'યમુનાજીના સામે કાંઠે, માંટ તાલુકો, જી. મથુરા (ઉત્તર પ્રદેશ)',
      contacts: [],
      mahatmy: 'ભાંડીરવડ લીલા સ્થાન.',
      directions: 'ભાંડીરવન, મથુરા',
      rules: [],
    ),
    BethakjiModel(
      id: '22',
      number: '22',
      name: 'શ્રી માનસરોવર બેઠકજી',
      address: 'માનસરોવર, માંટ, જી. મથુરા (ઉત્તર પ્રદેશ)',
      contacts: [],
      mahatmy: 'શ્રી રાધાજીના માન રોષનું પવિત્ર સરોવર.',
      directions: 'માનસરોવર, મથુરા',
      rules: [],
    ),
    BethakjiModel(
      id: '23',
      number: '23',
      name: 'શ્રી શૂકરક્ષેત્ર (સોરોંજી) બેઠકજી',
      address: 'સૌરભ ઘાટ (ગંગા તીર), સોરોં - 207403, જી. એટા (ઉત્તર પ્રદેશ)',
      contacts: [],
      mahatmy: 'વરાહ ભગવાનનું ક્ષેત્ર.',
      directions: 'સોરોં, ઉત્તર પ્રદેશ',
      rules: [],
    ),
    BethakjiModel(
      id: '24',
      number: '24',
      name: 'શ્રી ચિત્રકૂટ બેઠકજી',
      address: 'કામતાનાથ પર્વત પર, ચિત્રકૂટ - 485336, જી. સતના (મધ્ય પ્રદેશ)',
      contacts: [],
      mahatmy: 'ચિત્રકૂટ પવિત્ર પર્વત સ્થાન.',
      directions: 'ચિત્રકૂટ, મધ્ય પ્રદેશ',
      rules: [],
    ),
    BethakjiModel(
      id: '25',
      number: '25',
      name: 'શ્રી અયોધ્યાજી બેઠકજી',
      address: 'રામઘાટ રોડ, અયોધ્યા - 224123, જી. અયોધ્યા (ઉત્તર પ્રદેશ)',
      contacts: [],
      mahatmy: 'શ્રી રામ જન્મભૂમિ અયોધ્યા ધામ.',
      directions: 'રામઘાટ રોડ, અયોધ્યા',
      rules: [],
    ),
    BethakjiModel(
      id: '26',
      number: '26',
      name: 'શ્રી નૈમિષારણ્ય બેઠકજી',
      address: 'વેદવ્યાસ આશ્રમ પાસે, નૈમિષારણ્ય, જી. સીતાપુર (ઉત્તર પ્રદેશ)',
      contacts: [],
      mahatmy: 'તપોભૂમિ નૈમિષારણ્ય.',
      directions: 'સીતાપુર, ઉત્તર પ્રદેશ',
      rules: [],
    ),
    BethakjiModel(
      id: '27',
      number: '27',
      name: 'શ્રી કાશી પુરુષોત્તમદાસ બેઠકજી',
      address: 'જટનવાડ, વારાણસી (કાશી) - 221001 (ઉત્તર પ્રદેશ)',
      contacts: [],
      mahatmy: 'સેવક પુરુષોત્તમદાસના ઘરમાં બેઠકજી.',
      directions: 'કાશી વારાણસી',
      rules: [],
    ),
    BethakjiModel(
      id: '28',
      number: '28',
      name: 'શ્રી હનુમાન ઘાટ બેઠકજી (કાશી)',
      address: 'હનુમાન ઘાટ, વારાણસી - 221001 (ઉત્તર પ્રદેશ)',
      contacts: [],
      mahatmy: 'ગંગા કિનારે હનુમાન ઘાટ પર સ્થિત.',
      directions: 'હનુમાન ઘાટ, કાશી',
      rules: [],
    ),
    BethakjiModel(
      id: '29',
      number: '29',
      name: 'શ્રી હરિહર ક્ષેત્ર બેઠકજી (હાજીપુર)',
      address: 'મગરહટ્ટા ચોક, હાજીપુર - 844001, જી. વૈશાલી (બિહાર)',
      contacts: [],
      mahatmy: 'ગજેન્દ્ર મોક્ષ ક્ષેત્ર હાજીપુર.',
      directions: 'હાજીપુર, બિહાર',
      rules: [],
    ),
    BethakjiModel(
      id: '30',
      number: '30',
      name: 'શ્રી જનકપુર બેઠકજી (ગુપ્ત બેઠક)',
      address: 'માણેક તળાવ, જનકપુર, જી. વૈશાલી (બિહાર)',
      contacts: [],
      mahatmy: 'માતા જાનકીનું પવિત્ર સ્થાન.',
      directions: 'જનકપુર, બિહાર',
      rules: [],
    ),

    // 31 to 40
    BethakjiModel(
      id: '31',
      number: '31',
      name: 'શ્રી ગંગાસાગર બેઠકજી',
      address: 'કપિલ આશ્રમ પાસે, કાકદ્વીપ બેટ (પશ્ચિમ બંગાળ)',
      contacts: [],
      mahatmy: 'કપિલ મુનિ આશ્રમ પાસે ગંગાસાગર સંગમ.',
      directions: 'કોલકાતાથી 100 કિ.મી.',
      rules: [],
    ),
    BethakjiModel(
      id: '32',
      number: '32',
      name: 'શ્રી ચંપારણ્ય પ્રાગટ્ય બેઠકજી',
      address: 'ચંપારણ્ય - 493885, જી. રાયપુર (છત્તીસગઢ)',
      contacts: [
        {'label': 'ઓફિસ', 'phone': '0771-2777121'},
      ],
      mahatmy: 'શ્રી વલ્લભાચાર્ય મહાપ્રભુજીનું પ્રાગટ્ય સ્થાન.',
      directions: 'રાજિમ વાયા રાયપુર',
      rules: ['મંદિરમાં શિસ્ત જાળવવી'],
    ),
    BethakjiModel(
      id: '33',
      number: '33',
      name: 'શ્રી ચંપારણ્ય છઠ્ઠી બેઠકજી',
      address: 'છઠ્ઠી સ્થાન, ચંપારણ્ય - 493885, જી. રાયપુર (છત્તીસગઢ)',
      contacts: [],
      mahatmy: 'મહાપ્રભુજીના જન્મના છઠ્ઠા દિવસ ઉત્સવ સ્થાન.',
      directions: 'ચંપારણ્ય',
      rules: [],
    ),
    BethakjiModel(
      id: '34',
      number: '34',
      name: 'શ્રી જગન્નાથપુરી બેઠકજી',
      address: 'ગ્રાન્ટ રોડ, પુરી - 752001 (ઓડિશા)',
      contacts: [],
      mahatmy: 'શ્રી જગન્નાથ ધામમાં મહાપ્રસાદનો મહિમા પ્રગટ કર્યો.',
      directions: 'પુરી ઓડિશા',
      rules: [],
    ),
    BethakjiModel(
      id: '35',
      number: '35',
      name: 'શ્રી પંઢરપુર બેઠકજી',
      address: 'ચંદ્રભાગા નદી કિનારે, પંઢરપુર - 413304 (મહારાષ્ટ્ર)',
      contacts: [],
      mahatmy: 'શ્રી વિઠ્ઠલનાથજીનું ધામ.',
      directions: 'પુણેથી 200 કિ.મી.',
      rules: [],
    ),
    BethakjiModel(
      id: '36',
      number: '36',
      name: 'શ્રી નાસિક તપોવન બેઠકજી',
      address: 'પંચવટી, નાસિક - 422001 (મહારાષ્ટ્ર)',
      contacts: [],
      mahatmy: 'ગોદાવરી તીર પંચવટી તપોવન.',
      directions: 'નાસિક પંચવટી',
      rules: [],
    ),
    BethakjiModel(
      id: '37',
      number: '37',
      name: 'શ્રી પન્ના નરસિંહજી બેઠકજી',
      address: 'મંગલગિરી સ્ટેશન પાસે, વિજયવાડા (આંધ્રપ્રદેશ)',
      contacts: [],
      mahatmy: 'મંગલગિરી નરસિંહ ભગવાન સ્થાન.',
      directions: 'વિજયવાડા',
      rules: [],
    ),
    BethakjiModel(
      id: '38',
      number: '38',
      name: 'શ્રી લક્ષ્મણબાલાજી બેઠકજી (તિરુપતિ)',
      address: 'શંકર મઠ પાસે, તિરુમાલા - 517504 (આંધ્રપ્રદેશ)',
      contacts: [
        {'label': 'મઠ ઓફિસ', 'phone': '0877-2277317'},
      ],
      mahatmy: 'તિરુમાલા પર્વત પર સ્થિત બેઠકજી.',
      directions: 'તિરુપતિ તિરુમાલા',
      rules: [],
    ),
    BethakjiModel(
      id: '39',
      number: '39',
      name: 'શ્રી શ્રીરંગમ બેઠકજી',
      address: '21, નોર્થ ગેટ, શ્રીરંગમ, તિરુચિરાપલ્લી - 620006 (તમિલનાડુ)',
      contacts: [],
      mahatmy: 'શ્રી રંગનાથજી ધામ.',
      directions: 'ત્રિચી શ્રીરંગમ',
      rules: [],
    ),
    BethakjiModel(
      id: '40',
      number: '40',
      name: 'શ્રી વિષ્ણુકાંચી બેઠકજી',
      address: 'વેગવતી નદી કિનારે, કાંચીપુરમ - 631503 (તમિલનાડુ)',
      contacts: [],
      mahatmy: 'કાંચીપુરમ પવિત્ર ક્ષેત્ર.',
      directions: 'ચેન્નઈથી 72 કિ.મી.',
      rules: [],
    ),

    // 41 to 50
    BethakjiModel(
      id: '41',
      number: '41',
      name: 'શ્રી સેતુબંધ રામેશ્વર બેઠકજી',
      address: 'રામેશ્વરમ, જી. રામનાથપુરમ (તમિલનાડુ)',
      contacts: [],
      mahatmy: 'દક્ષિણ ધામ રામેશ્વરમ.',
      directions: 'રામેશ્વરમ',
      rules: [],
    ),
    BethakjiModel(
      id: '42',
      number: '42',
      name: 'શ્રી મલયાચલ પર્વત બેઠકજી (ગુપ્ત)',
      address: 'મલયાચલ પર્વત (કોઈમ્બતુર વાયા, તમિલનાડુ)',
      contacts: [],
      mahatmy: 'મલયાચલ પર્વત ગુપ્ત બેઠકજી.',
      directions: 'કોઈમ્બતુર',
      rules: [],
    ),
    BethakjiModel(
      id: '43',
      number: '43',
      name: 'શ્રી લોહગઢ (ગોવા) બેઠકજી',
      address: 'રુદ્રેશ્વર મંદિર પાસે, હરવલે, પંજી (ગોવા)',
      contacts: [],
      mahatmy: 'ગોવા લોહગઢ ક્ષેત્ર.',
      directions: 'પંજી, ગોવા',
      rules: [],
    ),
    BethakjiModel(
      id: '44',
      number: '44',
      name: 'શ્રી તામ્રપર્ણી નદી બેઠકજી',
      address: 'તામ્રપર્ણી નદી કિનારે (તમિલનાડુ)',
      contacts: [],
      mahatmy: 'તામ્રપર્ણી નદી તીર ગુપ્ત બેઠકજી.',
      directions: 'તિરુનેલવેલી ક્ષેત્ર',
      rules: [],
    ),
    BethakjiModel(
      id: '45',
      number: '45',
      name: 'શ્રી કૃષ્ણા નદી બેઠકજી',
      address: 'કૃષ્ણા ધામ, વાડી જંકશન, રાયચૂર પાસે (આંધ્રપ્રદેશ)',
      contacts: [],
      mahatmy: 'કૃષ્ણા નદી તીર.',
      directions: 'રાયચૂર પાસે',
      rules: [],
    ),
    BethakjiModel(
      id: '46',
      number: '46',
      name: 'શ્રી પંપા સરોવર બેઠકજી',
      address: 'હંપી ક્ષેત્ર, કર્ણાટક',
      contacts: [],
      mahatmy: 'પંપા સરોવર હંપી રામાયણ કાળ સ્થાન.',
      directions: 'હંપી, કર્ણાટક',
      rules: [],
    ),
    BethakjiModel(
      id: '47',
      number: '47',
      name: 'શ્રી પદ્મનાભજી બેઠકજી',
      address: 'તિરુવનંતપુરમ (કેરળ)',
      contacts: [],
      mahatmy: 'શ્રી પદ્મનાભસ્વામી મંદિર ક્ષેત્ર.',
      directions: 'ત્રિવેન્દ્રમ કેરળ',
      rules: [],
    ),
    BethakjiModel(
      id: '48',
      number: '48',
      name: 'શ્રી જનાર્દન ક્ષેત્ર બેઠકજી',
      address: 'વરકલા (કેરળ)',
      contacts: [],
      mahatmy: 'જનાર્દનસ્વામી ક્ષેત્ર.',
      directions: 'વરકલા કેરળ',
      rules: [],
    ),
    BethakjiModel(
      id: '49',
      number: '49',
      name: 'શ્રી વિદ્યાનગર બેઠકજી',
      address: 'વિજયનગર (હંપી ક્ષેત્ર, કર્ણાટક)',
      contacts: [],
      mahatmy: 'શાસ્ત્રાર્થ વિજય સ્થાન વિદ્યાનગર.',
      directions: 'કર્ણાટક',
      rules: [],
    ),
    BethakjiModel(
      id: '50',
      number: '50',
      name: 'શ્રી ત્રિલોકભાન બેઠકજી (ગુપ્ત)',
      address: 'દક્ષિણ ભારત (તમિલનાડુ)',
      contacts: [],
      mahatmy: 'ગુપ્ત સ્થાન.',
      directions: 'તમિલનાડુ',
      rules: [],
    ),

    // 51 to 60 (Gujarat Starts)
    BethakjiModel(
      id: '51',
      number: '51',
      name: 'શ્રી તોતાદ્રિ પર્વત બેઠકજી',
      address: 'નાગુનેરી, તિરુનેલવેલી પાસે (તમિલનાડુ)',
      contacts: [],
      mahatmy: 'તોતાદ્રિ મઠ ક્ષેત્ર.',
      directions: 'તિરુનેલવેલીથી 30 કિ.મી.',
      rules: [],
    ),
    BethakjiModel(
      id: '52',
      number: '52',
      name: 'શ્રી દર્ભશયન બેઠકજી',
      address: 'આદિસેતુ ગામ, રામનાથપુરમ (તમિલનાડુ)',
      contacts: [],
      mahatmy: 'રામનાથપુરમ દર્ભશયન રામજી સ્થાન.',
      directions: 'તમિલનાડુ',
      rules: [],
    ),
    BethakjiModel(
      id: '53',
      number: '53',
      name: 'શ્રી સુરત બેઠકજી (અશ્વિનીકુમાર)',
      address: 'અશ્વિનીકુમાર ઘાટ, તાપી નદી કિનારે, સુરત - 395008 (ગુજરાત)',
      contacts: [],
      mahatmy: 'સુરત તાપી તીર અશ્વિનીકુમાર ઘાટ.',
      directions: 'અશ્વિનીકુમાર ઘાટ, સુરત',
      rules: ['શાંતિ જાળવવી'],
    ),
    BethakjiModel(
      id: '54',
      number: '54',
      name: 'શ્રી ભરૂચ બેઠકજી',
      address: 'જિલ્લા પંચાયત બાજુમાં, સ્ટેશન રોડ, ભરૂચ - 392001 (ગુજરાત)',
      contacts: [
        {'label': 'ઓફિસ', 'phone': '02642-264660'},
      ],
      mahatmy: 'નર્મદા તીર ભરૂચ ધામ.',
      directions: ' સ્ટેશન રોડ, ભરૂચ',
      rules: [],
    ),
    BethakjiModel(
      id: '55',
      number: '55',
      name: 'શ્રી મોરબી બેઠકજી',
      address: 'મચ્છુ નદી કિનારે, L.E. કોલેજ પાછળ, મોરબી - 363641 (ગુજરાત)',
      contacts: [
        {'label': 'ઓફિસ', 'phone': '02822-240335'},
      ],
      mahatmy: 'મચ્છુ નદી તીર મોરબી.',
      directions: 'L.E. કોલેજ પાછળ, મોરબી',
      rules: [],
    ),
    BethakjiModel(
      id: '56',
      number: '56',
      name: 'શ્રી જામનગર (નવાનગર) બેઠકજી',
      address: 'નાગમતી નદી કિનારે, કાલવડ રોડ, જામનગર - 361005 (ગુજરાત)',
      contacts: [
        {'label': 'ઓફિસ', 'phone': '0288-2570671'},
      ],
      mahatmy: 'નાગમતી નદી તીરે જામનગર.',
      directions: 'કાલવડ રોડ, જામનગર',
      rules: [],
    ),
    BethakjiModel(
      id: '57',
      number: '57',
      name: 'શ્રી જામખંભાળિયા બેઠકજી',
      address: 'સ્ટેશન રોડ, જામખંભાળિયા - 361305, જી. દેવભૂમિ દ્વારકા (ગુજરાત)',
      contacts: [],
      mahatmy: 'ખંભાળિયા બેઠકજી.',
      directions: 'જામખંભાળિયા',
      rules: [],
    ),
    BethakjiModel(
      id: '58',
      number: '58',
      name: 'શ્રી પિંડતારક (પિંડારા) બેઠકજી',
      address: 'દુર્વાસા ઋષિ આશ્રમ, પિંડારા, જી. દેવભૂમિ દ્વારકા (ગુજરાત)',
      contacts: [],
      mahatmy: 'પિંડતારક તીર્થ દુર્વાસા આશ્રમ.',
      directions: 'ભાટિયાથી પિંડારા',
      rules: [],
    ),
    BethakjiModel(
      id: '59',
      number: '59',
      name: 'શ્રી મૂળ ગોમતી બેઠકજી',
      address: 'નાના ભવડા, તા. દ્વારકા, જી. દેવભૂમિ દ્વારકા (ગુજરાત)',
      contacts: [
        {'label': 'ઓફિસ', 'phone': '02892-234355'},
      ],
      mahatmy: 'મૂળ ગોમતી પવિત્ર ક્ષેત્ર.',
      directions: 'દ્વારકા પાસે',
      rules: [],
    ),
    BethakjiModel(
      id: '60',
      number: '60',
      name: 'શ્રી દ્વારકા હરિકુંડ બેઠકજી',
      address: 'ગોમતી નદી તીરે, હરિકુંડ ઉપર, દ્વારકા - 361335 (ગુજરાત)',
      contacts: [
        {'label': 'ઓફિસ', 'phone': '02892-234825'},
      ],
      mahatmy: 'દ્વારકાધીશ ધામ ગોમતી તીર હરિકુંડ.',
      directions: 'દ્વારકા તીર્થ',
      rules: [],
    ),

    // 61 to 70
    BethakjiModel(
      id: '61',
      number: '61',
      name: 'શ્રી ગોપીતળાવ બેઠકજી',
      address: 'ગોપી તળાવ, દ્વારકા - 361335 (ગુજરાત)',
      contacts: [],
      mahatmy: 'ગોપી ચંદન પવિત્ર સ્થળ ગોપી તળાવ.',
      directions: 'દ્વારકાથી 20 કિ.મી.',
      rules: [],
    ),
    BethakjiModel(
      id: '62',
      number: '62',
      name: 'શ્રી બેટ શંખોદ્ધાર બેઠકજી',
      address: 'શંખ તળાવ પાસે, બેટ દ્વારકા (ગુજરાત)',
      contacts: [],
      mahatmy: 'બેટ દ્વારકા શંખોદ્ધાર ક્ષેત્ર.',
      directions: 'ઓખાથી બોટ દ્વારા બેટ દ્વારકા',
      rules: [],
    ),
    BethakjiModel(
      id: '63',
      number: '63',
      name: 'શ્રી નારાયણ સરોવર બેઠકજી',
      address: 'નારાયણ સરોવર, તા. લખપત, જી. કચ્છ (ગુજરાત)',
      contacts: [],
      mahatmy: 'પંચ સરોવરમાંનું એક પવિત્ર નારાયણ સરોવર.',
      directions: 'કચ્છ નારાયણ સરોવર',
      rules: [],
    ),
    BethakjiModel(
      id: '64',
      number: '64',
      name: 'શ્રી જૂનાગઢ (ગિરનાર) બેઠકજી',
      address: 'દામોદર કુંડ પાસે, જૂનાગઢ - 362001 (ગુજરાત)',
      contacts: [],
      mahatmy: 'ગિરનાર તળેટી દામોદર કુંડ.',
      directions: 'દામોદર કુંડ, જૂનાગઢ',
      rules: [],
    ),
    BethakjiModel(
      id: '65',
      number: '65',
      name: 'શ્રી પ્રભાસક્ષેત્ર (સોમનાથ) બેઠકજી',
      address: 'ત્રિવેણી સંગમ ઘાટ, પ્રભાસ પાટણ, સોમનાથ (ગુજરાત)',
      contacts: [],
      mahatmy: 'ત્રિવેણી સંગમ ક્ષેત્ર સોમનાથ.',
      directions: 'વેરાવળ સોમનાથ',
      rules: [],
    ),
    BethakjiModel(
      id: '66',
      number: '66',
      name: 'શ્રી માધવપુર બેઠકજી',
      address: 'કદમ કુંડ પાસે, માધવપુર ઘેડ, જી. પોરબંદર (ગુજરાત)',
      contacts: [],
      mahatmy: 'શ્રી કૃષ્ણ-રુકમિણી વિવાહ સ્થળ માધવપુર.',
      directions: 'પોરબંદર સોમનાથ હાઈવે',
      rules: [],
    ),
    BethakjiModel(
      id: '67',
      number: '67',
      name: 'શ્રી ગુપ્તપ્રયાગ બેઠકજી',
      address: 'ગુપ્તપ્રયાગ, તા. ઉના, જી. ગીર સોમનાથ (ગુજરાત)',
      contacts: [],
      mahatmy: 'ત્રિવેણી સંગમ તીર્થ ગુપ્તપ્રયાગ.',
      directions: 'દેલવાડા - ઉના રોડ',
      rules: [],
    ),
    BethakjiModel(
      id: '68',
      number: '68',
      name: 'શ્રી તગડી બેઠકજી',
      address: 'તગડી ગામ, ધંધૂકા પાસે, જી. અમદાવાદ (ગુજરાત)',
      contacts: [],
      mahatmy: 'ધંધૂકા પાસે આવેલ તગડી ગામ.',
      directions: 'ધંધૂકાથી તગડી',
      rules: [],
    ),
    BethakjiModel(
      id: '69',
      number: '69',
      name: 'શ્રી નરોડા બેઠકજી (અમદાવાદ)',
      address: 'બેઠકજી મંદિર, નરોડા, અમદાવાદ - 382330 (ગુજરાત)',
      contacts: [],
      mahatmy: 'અમદાવાદ નરોડા સ્થિત પ્રાચીન બેઠકજી.',
      directions: 'નરોડા, અમદાવાદ',
      rules: [],
    ),
    BethakjiModel(
      id: '70',
      number: '70',
      name: 'શ્રી ગોધરા બેઠકજી',
      address: 'રામસાગર તળાવ પાસે, ગોધરા - 389001 (ગુજરાત)',
      contacts: [],
      mahatmy: 'ગોધરા રામસાગર તળાવ કિનારે.',
      directions: 'ગોધરા નગર',
      rules: [],
    ),

    // 71 to 84
    BethakjiModel(
      id: '71',
      number: '71',
      name: 'શ્રી ખેરાળુ બેઠકજી',
      address: 'ખેરાળુ ગામ, જી. મહેસાણા (ગુજરાત)',
      contacts: [],
      mahatmy: 'ઉત્તર ગુજરાત ખેરાળુ.',
      directions: 'મહેસાણા ખેરાળુ',
      rules: [],
    ),
    BethakjiModel(
      id: '72',
      number: '72',
      name: 'શ્રી સિદ્ધપુર બેઠકજી',
      address: 'બિંદુ સરોવર તીર્થ, સિદ્ધપુર - 384151, જી. પાટણ (ગુજરાત)',
      contacts: [],
      mahatmy: 'માતૃશ્રાદ્ધ તીર્થ બિંદુ સરોવર.',
      directions: 'સિદ્ધપુર',
      rules: [],
    ),
    BethakjiModel(
      id: '73',
      number: '73',
      name: 'શ્રી અવંતિકાપુરી (ઉજ્જૈન) બેઠકજી',
      address: 'શિપ્રા નદી તીરે, ઉજ્જૈન - 456006 (મધ્ય પ્રદેશ)',
      contacts: [],
      mahatmy: 'સાંદીપનિ આશ્રમ તથા શિપ્રા તીર ઉજ્જૈન.',
      directions: 'ઉજ્જૈન શિપ્રા ઘાટ',
      rules: [],
    ),
    BethakjiModel(
      id: '74',
      number: '74',
      name: 'શ્રી પુષ્કર બેઠકજી',
      address: 'બ્રહ્મા મંદિર પાસે, પુષ્કરરાજ, જી. અજમેર (રાજસ્થાન)',
      contacts: [],
      mahatmy: 'તીર્થરાજ પુષ્કર સરોવર.',
      directions: 'અજમેરથી 14 કિ.મી.',
      rules: [],
    ),
    BethakjiModel(
      id: '75',
      number: '75',
      name: 'શ્રી કુરુક્ષેત્ર બેઠકજી',
      address: 'બ્રહ્મ સરોવર તીર, કુરુક્ષેત્ર - 136118 (હરિયાણા)',
      contacts: [],
      mahatmy: 'ગીતા ઉપદેશ ભૂમિ કુરુક્ષેત્ર.',
      directions: 'હરિયાણા',
      rules: [],
    ),
    BethakjiModel(
      id: '76',
      number: '76',
      name: 'શ્રી હરિદ્વાર (કનખલ) બેઠકજી',
      address: 'રામઘાટ, કનખલ, હરિદ્વાર - 249408 (ઉત્તરાખંડ)',
      contacts: [],
      mahatmy: 'ગંગા તીર હરિદ્વાર કનખલ.',
      directions: 'હરિદ્વાર કનખલ',
      rules: [],
    ),
    BethakjiModel(
      id: '77',
      number: '77',
      name: 'શ્રી બદ્રિકાશ્રમ બેઠકજી',
      address: 'અલકનંદા તીર, બદ્રીનાથ ધામ - 246422 (ઉત્તરાખંડ)',
      contacts: [],
      mahatmy: 'હિમાલય સ્થિત બદ્રીનાથ ધામ.',
      directions: 'બદ્રીનાથ ઉત્તરાખંડ',
      rules: [],
    ),
    BethakjiModel(
      id: '78',
      number: '78',
      name: 'શ્રી કેદારનાથ બેઠકજી',
      address: 'કેદારનાથ ધામ - 246445 (ઉત્તરાખંડ)',
      contacts: [],
      mahatmy: 'કેદારનાથ પવિત્ર ધામ.',
      directions: 'કેદારનાથ',
      rules: [],
    ),
    BethakjiModel(
      id: '79',
      number: '79',
      name: 'શ્રી વ્યાસાશ્રમ બેઠકજી',
      address: 'માણા ગામ પાસે, બદ્રીનાથ (ઉત્તરાખંડ)',
      contacts: [],
      mahatmy: 'વેદવ્યાસજીની ગુફા પાસે.',
      directions: 'માણા ગામ, બદ્રીનાથ',
      rules: [],
    ),
    BethakjiModel(
      id: '80',
      number: '80',
      name: 'શ્રી હિમાલય પર્વત બેઠકજી (ગુપ્ત)',
      address: 'હિમાલય પર્વત ક્ષેત્ર (ઉત્તરાખંડ)',
      contacts: [],
      mahatmy: 'હિમાલય ગુપ્ત તપોભૂમિ.',
      directions: 'ઉત્તરાખંડ',
      rules: [],
    ),
    BethakjiModel(
      id: '81',
      number: '81',
      name: 'શ્રી વ્યાસગંગા બેઠkજી',
      address: 'વ્યાસ ગંગા તીર (ઉત્તરાખંડ)',
      contacts: [],
      mahatmy: 'વ્યાસ ગંગા તીર્થ.',
      directions: 'ઉત્તરાખંડ',
      rules: [],
    ),
    BethakjiModel(
      id: '82',
      number: '82',
      name: 'શ્રી મન્દરાચલ પર્વત બેઠકજી',
      address: 'મન્દરાચલ પર્વત (બીહાર / ઝારખંડ ક્ષેત્ર)',
      contacts: [],
      mahatmy: 'સમુદ્ર મંથન પર્વત સ્થાન.',
      directions: 'મન્દરાચલ',
      rules: [],
    ),
    BethakjiModel(
      id: '83',
      number: '83',
      name: 'શ્રી અડેલ ત્રિવેણી બેઠકજી',
      address: 'અડેલ ગામ, પ્રયાગરાજ (અલાહાબાદ) - 211008 (ઉત્તર પ્રદેશ)',
      contacts: [],
      mahatmy: 'શ્રી મહાપ્રભુજીએ અહીં લાંબો સમય નિવાસ કર્યો હતો.',
      directions: 'પ્રયાગરાજ સંગમ પાર અડેલ',
      rules: [],
    ),
    BethakjiModel(
      id: '84',
      number: '84',
      name: 'શ્રી ચરણાટ (ચરણાંદ્રી) બેઠકજી',
      address: 'ચરણાટ ગામ, ચુનાર પાસે, વારાણસી ક્ષેત્ર (ઉત્તર પ્રદેશ)',
      contacts: [],
      mahatmy: 'શ્રી મહાપ્રભુજીની ૮૪મી પૂર્ણાહુતિ બેઠકજી.',
      directions: 'ચુનાર વારાણસી',
      rules: [],
    ),
  ];

  Future<Database> get database async {
    if (_database != null) return _database!;
    _database = await initDatabase();
    return _database!;
  }

  Future<Database> initDatabase() async {
    String path = join(await getDatabasesPath(), 'bethakji_yadi.db');

    const String sql = '''
    CREATE TABLE bethakji (
      id TEXT PRIMARY KEY,
      number TEXT,
      name TEXT NOT NULL,
      address TEXT,
      contacts TEXT,
      mahatmy TEXT,
      directions TEXT,
      rules TEXT
    )
    ''';

    return await openDatabase(
      path,
      version: 1,
      onCreate: (db, version) async {
        await db.execute(sql);

        // Batch insert all 84 Bethakjis efficiently
        Batch batch = db.batch();
        for (var item in bethakji84List) {
          batch.insert('bethakji', item.toMap());
        }
        await batch.commit(noResult: true);
      },
    );
  }

  // Fetch all records
  Future<List<BethakjiModel>> getAllBethakji() async {
    final db = await database;
    final List<Map<String, dynamic>> maps = await db.query('bethakji');

    return List.generate(maps.length, (i) {
      return BethakjiModel.fromMap(maps[i]);
    });
  }

  // Insert or update individual item
  Future<int> insertBethakji(BethakjiModel bethakji) async {
    final db = await database;
    return await db.insert(
      'bethakji',
      bethakji.toMap(),
      conflictAlgorithm: ConflictAlgorithm.replace,
    );
  }
}
